CREATE TABLE [dbo].[Report]
(
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    [Key] NVARCHAR(25) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Procedure] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NOT NULL
)